server:
  port: 0
spring:
  application:
    name: userService
  ## MongoDB Properties
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      database: user
      port: 27017
      host: {MONGO_HOST}
      auto-index-creation: true
  ## Zipkin and Sleuth Properties
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/zipkin}
  sleuth:
    sampler:
      probability: 1.0

## Eureka Properties
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_IN>
    fetch-registry: true
    register-with-eureka: true

# JWT properties
jwt:
  secret:
    key: ${SECRET_KEY:secret_secret_secret_secret_secret_secret_secret_secret_secret_secret}
