server:
  port: ${SERVER_PORT_EUREKA:8761}

spring:
  application:
    name: eureka-server
  # Zipkin Properties
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411}
  # Sleuth Properties
  sleuth:
    sampler:
      probability: 1.0

# Eureka Properties
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: true
